spring:
 profiles:
  active: -dev222
   
---

spring:
 profiles: dev   #开发环境
 application:
  name: microservicecloud-config-ym-dev
  
---

spring:
 profiles: test #测试环境
 application:
  name: microservicecloud-config-ym-test
